# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: What I Learn
title: What I Learn
email: ej88ej@gmail.com
description: '#web #backend #angularjs #nodejs #fullstack'
#url: http://whatilearn.com/
#baseurl: "" # the subpath of your site, e.g. /blog
#twitter_username: jekyllrb
#github_username:  jeonghwan-kim

# Build settings
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
